[package]
name = "apprun-rust-wasm"
version = "0.1.0"
authors = ["Yiyi Sun <yiyisun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
